services:
  chirpstack-gateway-os:
    build:
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - ./openwrt:/workdir
    ulimits:
      nofile:
        soft: 1024
        hard: 262144
