# Logging.
[logging]
  level="info"


# PostgreSQL configuration.
[postgresql]
  dsn="postgres://chirpstack:chirpstack@localhost/chirpstack?sslmode=disable"
  max_open_connections=10
  min_idle_connections=0


[redis]
  servers=[
    "redis://localhost/",
  ]


[network]
  net_id="000000"
  enabled_regions=[
    "as923",
    "as923_2",
    "as923_3",
    "as923_4",
    "au915_0",
    "cn779",
    "eu433",
    "eu868",
    "in865",
    "ism2400",
    "kr920",
    "ru864",
    "us915_0",
    "us915_1",
  ]


[api]
  bind="0.0.0.0:8080"

  # Secret.
  #
  # This secret is used for generating login and API tokens, make sure this
  # is never exposed. Changing this secret will invalidate all login and API
  # tokens. The following command can be used to generate a random secret:
  #   openssl rand -base64 32
  secret="you-must-replace-this"


[integration]
  enabled=["mqtt"]

  [integration.mqtt]
    server="tcp://localhost:1883/"
    json=true
