[logging]
  level="info"

[postgresql]
  dsn="postgres://chirpstack:chirpstack@localhost/chirpstack?sslmode=disable"

[redis]
  servers=[
    "redis://localhost/",
  ]

[network]
  net_id="000000"
  enabled_regions=[
    "as923",
    "as923_2",
    "as923_3",
    "as923_4",
    "au915_0",
    "au915_1",
    "au915_2",
    "au915_3",
    "au915_4",
    "au915_5",
    "au915_6",
    "au915_7",
    "cn779",
    "eu433",
    "eu868",
    "in865",
    "ism2400",
    "kr920",
    "ru864",
    "us915_0",
    "us915_1",
    "us915_2",
    "us915_3",
    "us915_4",
    "us915_5",
    "us915_6",
    "us915_7",
  ]

[api]
  bind="0.0.0.0:8080"

  # Secret.
  #
  # This secret is used for generating login and API tokens, make sure this
  # is never exposed. Changing this secret will invalidate all login and API
  # tokens. The following command can be used to generate a random secret:
  #   openssl rand -base64 32
  secret="you-must-replace-this"


[integration]
  enabled=["mqtt"]

  [integration.mqtt]
    server="tcp://localhost:1883/"
    json=true

    [integration.mqtt.client]
    client_cert_lifetime="365days"
    ca_cert="/etc/chirpstack/certs/ca.pem"
    ca_key="/etc/chirpstack/certs/ca-key.pem"

[gateway]
  client_cert_lifetime="365days"
  ca_cert="/etc/chirpstack/certs/ca.pem"
  ca_key="/etc/chirpstack/certs/ca-key.pem"
