[[regions]]
  name="us915_2"
  common_name="US915"

  [regions.gateway]

    [regions.gateway.backend]
      enabled="mqtt"

      [regions.gateway.backend.mqtt]
        event_topic="us915_2/gateway/+/event/+"
        command_topic="us915_2/gateway/{{ gateway_id }}/command/{{ command }}"
        server="tcp://localhost:1883"
        clean_session=true

    [[regions.gateway.channels]]
      frequency=905500000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10]

    [[regions.gateway.channels]]
      frequency=905700000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10]

    [[regions.gateway.channels]]
      frequency=905900000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10]

    [[regions.gateway.channels]]
      frequency=906100000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10]

    [[regions.gateway.channels]]
      frequency=906300000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10]

    [[regions.gateway.channels]]
      frequency=906500000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10]

    [[regions.gateway.channels]]
      frequency=906700000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10]

    [[regions.gateway.channels]]
      frequency=906900000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10]

    [[regions.gateway.channels]]
      frequency=906200000
      bandwidth=500000
      modulation="LORA"
      spreading_factors=[8]

  [regions.network]
    rx1_delay=1
    rx2_dr=8
    rx2_frequency=923300000
    min_dr=0
    max_dr=3
    enabled_uplink_channels=[16, 17, 18, 19, 20, 21, 22, 23, 66]

    [regions.network.class_b]
      ping_slot_dr=8
