[[regions]]
  id="in865"
  description="IN865"
  common_name="IN865"

  [regions.gateway]

    [regions.gateway.backend]

      enabled="mqtt"

      [regions.gateway.backend.mqtt]
        topic_prefix="in865"
        server="tcp://localhost:1883"
        clean_session=true

    [[regions.gateway.channels]]
      frequency=865062500
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=865402500
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=865985000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

  [regions.network]
    rx1_delay=1
    rx2_dr=2
    rx2_frequency=866550000
    min_dr=0
    max_dr=5

    [regions.network.class_b]
      ping_slot_dr=0
