[[regions]]
  id="ism2400"
  description="ISM2400"
  common_name="ISM2400"

  [regions.gateway]

    [regions.gateway.backend]
      enabled="mqtt"

      [regions.gateway.backend.mqtt]
        topic_prefix="ism2400"
        server="tcp://localhost:1883"
        clean_session=true

    [[regions.gateway.channels]]
      frequency=2403000000
      bandwidth=812000
      modulation="LORA"
      spreading_factors=[12]

    [[regions.gateway.channels]]
      frequency=2479000000
      bandwidth=812000
      modulation="LORA"
      spreading_factors=[12]

    [[regions.gateway.channels]]
      frequency=2425000000
      bandwidth=812000
      modulation="LORA"
      spreading_factors=[12]

  [regions.network]
    rx1_delay=1
    rx2_dr=0
    rx2_frequency=2423000000
    min_dr=0
    max_dr=7

    [regions.network.class_b]
      ping_slot_dr=0
