[[regions]]
  id="as923_4"
  description="AS923-4"
  common_name="AS923_4"

  [regions.gateway]

    [regions.gateway.backend]
      enabled="mqtt"

      [regions.gateway.backend.mqtt]
        topic_prefix="as923_4"
        server="tcp://localhost:1883"
        clean_session=true

    [[regions.gateway.channels]]
      frequency=917300000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=917500000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

  [regions.network]
    rx1_delay=1
    rx1_dr_offset=0
    rx2_dr=2
    rx2_frequency=917300000
    min_dr=0
    max_dr=5

    [regions.network.class_b]
      ping_slot_dr=0
